version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 4200 -b '0.0.0.0'
    volumes:
      - .:/fullstack_labs_exercise
    ports:
      - "4200:4200"
    depends_on:
      - db