# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79855e738c4cd8e59bcd8129b4fb276e0f98d36389637f65fc33fbc2d333fac1c159e1d16476a62a954fa2369219b742727a0e149d87d017cc5fda55649bd984

test:
  secret_key_base: 79c6a899905ec4a87f84925f1e1bb066d731a5ee02b64ea449101e46ab25586892b82b3442b69a7ed356f68e1d956cc0785215f47ba79de240353cbc70be6d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
